version: '3'

services:
  dynamicproducts:
    image: dynamicproducts
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dynamicproducts-secure.entrypoints=websecure"
      - "traefik.http.routers.dynamicproducts-secure.rule=Host(`dynamic-products.kingofdog.de`)"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  proxy:
    external: true
